postgram/urls.py
#Django
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

#'PATH(url)', VISTA.FUNCION_A_REALIZAR (mirar alias en import), 'ALIAS DE URL'
urlpatterns = [ 
    path('admin/', admin.site.urls),

    path('', include(('posts.urls', 'posts'), namespace='posts')), #1ro: ubicacion del archivo url.py. 2do: a que app pertenece.

    path('users/', include(('users.urls', 'users'), namespace='users')), #1ro: ubicacion del archivo url.py. 2do: a que app pertenece.

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #lo ultimo para mostrar imagenes #ver settings.py MEDIA_ROOT y MEDIA_URL

posts/urls.py
"""Posts URLs."""

# Django
from django.urls import path

# Views
from posts import views

urlpatterns = [
    path(route='', view=views.PostsFeedView.as_view(), name='feed'),
    path(route='posts/new/', view=views.CreatePostView.as_view(), name='create'),
    path(route='posts/<int:pk>/', view=views.PostDetailView.as_view(), name='detail'),
    path(route='posts/<int:pk>/delete/', view=views.PostDeleteView.as_view(), name='delete')
]

posts/models.py
"""Posts models."""

#Django
from django.db import models
from django.contrib.auth.models import User

#Storage
from postgram.storage_backends import PublicMediaStorage, PrivateMediaStorage


class Post(models.Model):
    """Post model."""

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    profile = models.ForeignKey('users.Profile', on_delete=models.CASCADE) 

    title = models.CharField(max_length=255)
    photo = models.ImageField(upload_to='posts/photos', storage=PublicMediaStorage())

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        """Return title and username."""
        return '{} by @{}'.format(self.title, self.user.username)

posts/forms.py
"""Post forms."""

#Django
from django import forms

#Models
from posts.models import Post


class PostForm(forms.ModelForm):
    """Post model form."""

    class Meta:
        """Form settings."""

        model = Post
        fields = ('user', 'profile', 'title', 'photo')

posts/views.py
"""Posts views."""
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.views.generic import CreateView, DetailView, ListView, DeleteView
from django.urls import reverse_lazy

#Forms
from posts.forms import PostForm

#Models
from posts.models import Post
from posts.models import User


class PostsFeedView(LoginRequiredMixin, ListView):
    """Return all published posts."""

    template_name = 'posts/feed.html'
    model = Post
    ordering = ('-created',)
    paginate_by = 30
    context_object_name = 'posts'


class PostDetailView(LoginRequiredMixin, DetailView):
    """Return post detail."""

    template_name = 'posts/detail.html'
    queryset = Post.objects.all()
    context_object_name = 'post'


class CreatePostView(LoginRequiredMixin, CreateView):
    """Create a new post."""

    template_name = 'posts/new.html'
    form_class = PostForm
    success_url = reverse_lazy('posts:feed')

    def get_context_data(self, **kwargs):
        """Add user and profile to context."""
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        context['profile'] = self.request.user.profile
        return context
    

class PostDeleteView(DeleteView):
    "Delete a post"
    print("You are about to delete a post, men!")
    # import pdb; pdb.set_trace()
    template_name = 'posts/delete.html'
    model = Post
    success_url = reverse_lazy('posts:feed')

    def get_queryset(self):
        queryset = super(PostDeleteView, self).get_queryset()
        # import pdb; pdb.set_trace()
        self.queryset = queryset.filter(id=self.kwargs['pk'])
        return self.queryset

    def get_object(self, queryset=None):
        return self.get_queryset()

    def post(self, *args, **kwargs):
        self.items_to_delete = self.request.POST.getlist('itemsToDelete')
        if self.request.POST.get("confirm_delete"):
            queryset = self.get_queryset()
            queryset.delete()
            return HttpResponseRedirect(self.success_url)
        elif self.request.POST.get("cancel"):
            return HttpResponseRedirect(self.success_url)
        else:
            return self.get(self, *args, **kwargs)

templates/posts/delete.html
{% extends "base.html" %}

{% block head_content %}
    <title>postgram</title>
{% endblock%}

{% block container %}

    <br>
    <!-- <div class="col-sm-12 col-md-8 offset-md-2 mt-5 p-0 card text-center">
        <div class="card-header">
            <h5>Delete post</h5>
        </div>
        <div class="card-body">
          <p class="card-text">Are you sure you want to delete this post?</p>
          <button type="button" type="submit" class="btn btn-outline-danger">Delete</button>
          <a type="button" class="btn btn-outline-primary" href="{% url "posts:feed" %}">Close</a>
        </div>
      </div> -->

    <div class="col-sm-12 col-md-8 offset-md-2 mt-5 p-0 card text-center">
    <div class="card-header">
        <h5>Delete post</h5>
    </div>
    <div class="card-body">
        <p class="card-text">Are you sure you want to delete this post?</p>
        <form action="" method="post">
            {% csrf_token %}
            <ul>
                <input type="hidden" value="{{ id }}" name="postToDelete" />
            </ul>
            <input type="submit" class="btn btn-outline-danger" value="Delete" name="confirm_delete" />
            <input type="submit" class="btn btn-outline-primary" value="Cancel" name="cancel" href="{% url "posts:feed" %}"/>
        </form>
    </div>
    </div>

    <!-- <form action="" method="post">
        {% csrf_token %}
        <ul>
            <input type="hidden" value="{{ id }}" name="postToDelete" />
        </ul>
        <input type="submit" class="btn btn-outline-danger" value="Delete" name="confirm_delete" />
        <input type="submit" class="btn btn-outline-primary" value="Cancel" name="cancel" href="{% url "posts:feed" %}"/>
    </form> -->

{% endblock %}



<!-- <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete post?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form> -->

templates/posts/detail.html
{% extends "base.html" %}

{% block head_content %}
    <title>postgram</title>
{% endblock%}
<!DOCTYPE html>
{% block container %}

    <div class="container">
        <div class="row">
            {% include "posts/post_card.html" %}
        </div>
    </div>

{% endblock %}

templates/posts/feed.html
{% extends "base.html" %}

{% block head_content %}
    <title>postgram</title>
{% endblock%}

{% block container %}

    <div class="container">
        <div class="row">

            {% for post in posts %}
                {% include "posts/post_card.html" %}
            {% endfor %}
        </div>
    </div>

    {% include "pagination.html" %}

{% endblock %}

templates/posts/new.html
{% extends "base.html" %}

{% block head_content %}
<title>Create new post</title>
{% endblock %}

{% block container %}

    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-6 pt-3 pb-3" id="profile-box">
                <h4 class="mb-4">Post a new photo!</h4>

                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}

                    <input type="hidden" name="user" value="{{ user.pk}}" />
                    <input type="hidden" name="profile" value="{{ profile.pk }}" />

                    {# Website field #}
                    <div class="form-group">
                        <input
                            class="form-control {% if form.title.errors %}is-invalid{% endif %}"
                            type="text"
                            name="title"
                            placeholder="Title"
                        >
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>

                    {# Photo field #}
                    <div class="form-group">
                        <label>Choose your photo:</label>
                        <input
                            class="form-control {% if form.photo.errors %}is-invalid{% endif %}"
                            type="file"
                            name="photo"
                            placeholder="photo"
                        >
                        <div class="invalid-feedback">
                            {% for error in form.photo.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary btn-block mt-5">Publish!</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/posts/post_card.html
<div class="col-sm-12 col-md-8 offset-md-2 mt-5 p-0 post-container">
    <div class="media pt-3 pl-3 pb-1">
        <a href="{% url "users:detail" post.user.username %}">
            <img class="mr-3 rounded-circle" height="35" src="{{ post.profile.picture.url }}" alt="{{ post.user.get_full_name }}">
        </a>
        <div class="media-body">
            <p style="margin-top: 5px;">{{ post.user.get_full_name  }}</p>
        </div>
    </div>

    <img style="width: 100%;" src="{{ post.photo.url }}" alt="{{ post.title }}">

    <!-- <p class="mt-1 ml-2" >
        <a href="" style="color: #000; font-size: 20px;">
            <i class="far fa-heart"></i>
        </a> 30 likes
        <a href="{% url "posts:delete" post.id %}" %}">
            <i class="fa fa-trash" style="color:red; float: right; margin: 4px 16px 0px 8px;"></i>
            <button type="button" type="submit" class="btn btn-outline-danger" style="float: right; margin: 4px 16px 0px 8px;">Delete</button>
        </a>
    </p> -->

    <p class="ml-2 mt-2 mb-2">
        <b>{{ post.title }}</b> - <small>{{ post.created }}</small>
        {% if user == post.user %}
            <a href="{% url "posts:delete" post.id %}" %}">
                <i class="fa fa-trash" style="color:red; float: right; margin: 4px 16px 0px 8px;"></i>
            </a>
        {% endif %}
    </p>
</div>